version: '3.8'

services:
  mysql-db:
    image: mysql:8.0                               # MySQL 이미지 버전
    container_name: n4-delivery                   # 컨테이너 이름(보통 프로젝트 이름)
    environment:
      MYSQL_ROOT_PASSWORD: test1234                # MySQL root 비밀번호
      MYSQL_DATABASE: testdb                       # 기본 데이터베이스 이름
      MYSQL_USER: testuser                         # 사용자 이름
      MYSQL_PASSWORD: testpass                     # 사용자 비밀번호
    ports:
      - "3307:3306"                                # 로컬과 컨테이너 간 포트 연결
    volumes:
      - mysql_data:/var/lib/mysql                  # 데이터 영구 저장을 위한 볼륨

volumes:
  mysql_data:                                      # MySQL 데이터 볼륨